# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

development:
  adapter: postgresql
  database: eventaservo
  pool: 5
  timeout: 5000
  host: localhost
  username: eventaservo
  password: eventaservo

staging:
  adapter: postgresql
  database: <%= Rails.application.credentials.dig(:database, :staging, :database) %>
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= Rails.application.credentials.dig(:database, :staging, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :staging, :password) %>

production:
  adapter: postgresql
  database: <%= Rails.application.credentials.dig(:database, :production, :database) %>
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= Rails.application.credentials.dig(:database, :production, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :production, :password) %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: eventaservo_test
  pool: 5
  timeout: 5000
  host: localhost
  username: <%= Rails.application.credentials.dig(:database, :development, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :development, :password) %>
